# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://dadevillepearsons.com/"  # Include trailing slash

title = "Dadeville Pearsons"  # Comment out this line and Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.

copyright = "Copyright © 2024, James Taylor and decendants of John E. Pearson; all rights reserved."

# Allow Goldmark markdown render to retain and output HTML code snippets
[markup.goldmark.renderer]
  unsafe = true
  
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
themesDir = "./themes"
disqusShortname = ""

languageCode = 'en-us'
# DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

[menus]
config/_default/menus/menu.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "families"

[outputs]
home = ["HTML", "RSS", "JSON"]

{params]
config/_default/params.toml
