# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://dadevillepearsons.com/"  # Include trailing slash
# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2024, James Taylor and decendants of John E. Pearson; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "github.com/chipzoller/hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

 [menus]
 config/_default/menus/menu.en.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "families" # Unique to this site.

[outputs]
home = ["HTML", "RSS", "JSON"]
